### PR TITLE
Refactored AdvisoryLock to more extendable form

### PR DESCRIPTION
**Pull request by maciej-rosiek**
Enum usage on AdvisoryLock class is nice but doesn't seem to allow creating new types of locks (correct me if I'm wrong). With this implementation it doesn't look that nice but at least it's extendable.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zalando/java-sproc-wrapper/pull/17" target="_blank">ReviewNinja

**Comment by maciej-rosiek** [comment]
@psycho-ir I'm not sure if I understand fully, but this is the idea, to give developers possibility to use arbitrary values in annotation. AFAIK java doesn't provide better ways to do it and I'm not sure if abstract class would buy anything more here.

**Comment by Jan-M** [comment]
We also had the base class thing back in the days in believe.

Back then we went with the advisory lock via enum, because it made it easily visible what locks exist already and avoided mistakes in using a wrong ID. technically an integer field like the sprocId or now "lockId" is fine.

**Comment by psycho-ir** [comment]
@maciej-rosiek When you have an abstract class that validate the values on creation or in usage, Client won't be able to use unrelated adivsoryLockSprocId and adivsoryLockName anymore.

By abstract class i mean you can have (e.g. AbstractAdvisoryLock)

So instead of 


long adivsoryLockSprocId() default AdvisoryLock.NoLock.SPROC_ID;

String adivsoryLockName() default AdvisoryLock.NoLock.NAME;

we could write

AbstractAdvisoryLock advisoryLick() default NoLock;

AbstractAdvisoryLock is responsible to check the consistency between adivsoryLockSprocId and adivsoryLockName.

I hope i could explain it clearly :).

But at all i am agree with @Jan-M and i think extensibility is not a case for AdvisoryLock.

**Comment by maciej-rosiek** [comment]
I think this construct is not allowed in java: AbstractAdvisoryLock advisoryLick() default NoLock;
You can either have simple types like int or string, or enums (where abstract doesn't apply).

**Comment by psycho-ir** [comment]
Oh yes you are right. it is not possible. 
What about this approach: 
Class<? extends AbstractAdvisoryLock> advisoryLick() default NoLockImp.class;

Something like shardStrategy in SprocService

**Comment by maciej-rosiek** [comment]
Although what you are proposing makes sense at first, but it won't have any advantage over my implementation. At the end you would have somewhere in your project number of AdvisoryLock classes like this which in my opinion is not nice:

    public class NoLock implements AdvisoryLock {
        @Override
        public String getName() {
            return "NO_LOCK";
        }

        @Override
        public long getLockId() {
            return 0L;
        }
    }

**Comment by psycho-ir** [comment]
Yes, I am agree with you. having different classes with same structure and difference just on return values is not nice.

**Pull request merged**
